from pydantic import BaseModel, Field
from typing import Optional

class GOADocument(BaseModel):
    eg_none_check: Optional[str] = Field(..., description="Euro Guarding - None")
    eg_pmtg_check: Optional[str] = Field(..., description="Euro Guarding - Panel material - Tempered glass")
    eg_pnl_check: Optional[str] = Field(..., description="Euro Guarding - Panel material - Lexan")
    eg_stkw_check: Optional[str] = Field(..., description="Euro Guarding - Switch type - Key switch")
    eg_stm_check: Optional[str] = Field(..., description="Euro Guarding - Switch type - Magnetic")
    eg_sto_check: Optional[str] = Field(..., description="Euro Guarding - Switch type - Other")
    eg_tcnone_check: Optional[str] = Field(..., description="Euro Guarding - Top cover - None")
    eg_tcyes_check: Optional[str] = Field(..., description="Euro Guarding - Top cover - Yes")
    eg_rc_check: Optional[str] = Field(..., description="Euro Guarding - Reject cover")
    eg_rcnone_check: Optional[str] = Field(..., description="Euro Guarding - Reject cover - None")
    ci_chs_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Coder - hot stamp")
    ci_ci15_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Videojet - ink jet vj 1520")
    ci_cl_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Coder - laser")
    ci_cnone_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Coder - none")
    ci_ctj_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Coder - thermal ink jet")
    ci_lfe_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Laser - fume extraction")
    ci_lfm: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Laser - fume extraction model")
    ci_lo_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Laser - other")
    ci_lv_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Laser - videojet")
    ci_lvm: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Laser - videojet model")
    ci_p2d_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Print - 2d")
    ci_pbc_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Print - bar code")
    ci_pep_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Print - exp. date")
    ci_pl_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Print - lot")
    ci_pnone_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Print - none")
    ci_po_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Print - other")
    ci_ppo_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Print - package on")
    ci_v33_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Videojet - laser 3330")
    ci_v85_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Videojet - 8520")
    ci_vb_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - barcode")
    ci_vc_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - cognex")
    ci_vcom: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - comment")
    ci_vd651_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Videojet - dataflex 6530 (107wx75l)")
    ci_vd65_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Videojet -dataflex 6530 (53wx75l)")
    ci_vdxsx: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Videojet - for dx (rh) for sx (lh)")
    ci_vnone_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - none")
    ci_vo_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - other")
    ci_vocr_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - ocr")
    ci_vocv_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - ocv")
    ci_vos_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - orientation/ skew")
    ci_vow_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - on web")
    ci_vp_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - presence")
    ci_vqty: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - qty")
    ci_vpo_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - position/ placement")
    ci_vtq_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - torque")
    ci_ctt_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Coder - thermal transfer")
    ci_vob_check: Optional[str] = Field(..., description="Coding and Inspection System Specifications - Vision - on bottle")
    sk_1yr_check: Optional[str] = Field(..., description="Warranty & Install & Spares - Spare kit - 1yr")
    sk_2yr_check: Optional[str] = Field(..., description="Warranty & Install & Spares - Spare kit - 2yr")
    sk_none_check: Optional[str] = Field(..., description="Warranty & Install & Spares - Spare kit - none")
    stpc_none_check: Optional[str] = Field(..., description="Warranty & Install & Spares - Start-up commissioning - none")
    stpc_yes: Optional[str] = Field(..., description="Warranty & Install & Spares - Start-up commissioning - yes – # of days")
    wi_war1_check: Optional[str] = Field(..., description="Warranty & Install & Spares - Warranty - 1yr")
    wi_war2_check: Optional[str] = Field(..., description="Warranty & Install & Spares - Warranty - 2yr")
    wrts_y_check: Optional[str] = Field(..., description="Warranty & Install & Spares - Remote tech service - yes")
    wrts_none_check: Optional[str] = Field(..., description="Warranty & Install & Spares - Remote tech service - none")
    pt_pbc_check: Optional[str] = Field(..., description="Packaging & Transport - Packaging by - capmatic")
    pt_pbcu_check: Optional[str] = Field(..., description="Packaging & Transport - Packaging by - customer / not incl.")
    pt_ptc_check: Optional[str] = Field(..., description="Packaging & Transport - Packaging type - crate")
    pt_ptsw_check: Optional[str] = Field(..., description="Packaging & Transport - Packaging type -  sea worthy")
    pt_tcc_check: Optional[str] = Field(..., description="Packaging & Transport - Transport charges - capmatic")
    pt_tccu_check: Optional[str] = Field(..., description="Packaging & Transport - Transport charges - customer")
    vd_d_check: Optional[str] = Field(..., description="Validation Documents - Design Qualification (DQ) Documentation")
    vd_f_check: Optional[str] = Field(..., description="Validation Documents - Factory Acceptance Test (FAT) Protocol Package - Includes documentation, support, and customer review")
    vd_fd_check: Optional[str] = Field(..., description="Validation Documents - Functional/Design Specification (FS/DS)")
    vd_h_check: Optional[str] = Field(..., description="Validation Documents - Hardware/Software Design Specification (HDS/SDS)")
    vd_i_check: Optional[str] = Field(..., description="Validation Documents - Installation/Operational Qualification (IQ/OQ)")
    vd_s_check: Optional[str] = Field(..., description="Validation Documents - Site Acceptance Test (SAT) Protocol Package - Includes documentation, support, and customer review")
    ls_a3p_check: Optional[str] = Field(..., description="Labeling System Specifications - Application sys - 3-panel")
    ls_a4p_check: Optional[str] = Field(..., description="Labeling System Specifications - Application sys - 4-panel")
    ls_a5p_check: Optional[str] = Field(..., description="Labeling System Specifications - Application sys - 5-panel")
    ls_abqty: Optional[str] = Field(..., description="Labeling System Specifications - Application sys - belts qty")
    ls_acl_check: Optional[str] = Field(..., description="Labeling System Specifications - Application sys - case label")
    ls_ap_check: Optional[str] = Field(..., description="Labeling System Specifications - Application sys - prism")
    ls_atl_check: Optional[str] = Field(..., description="Labeling System Specifications - Arm type - \"l\" shaped")
    ls_ats_check: Optional[str] = Field(..., description="Labeling System Specifications - Arm type - standard")
    ls_awa_check: Optional[str] = Field(..., description="Labeling System Specifications - Application sys - wrap around")
    ls_awb_check: Optional[str] = Field(..., description="Labeling System Specifications - Application sys - wipe front & back")
    ls_awp_check: Optional[str] = Field(..., description="Labeling System Specifications - Application sys - wrap around in puck")
    ls_ee_check: Optional[str] = Field(..., description="Labeling System Specifications - eagle eye plus sensor (clr label)")
    ls_lhdx_check: Optional[str] = Field(..., description="Labeling System Specifications - Label head orientation - dx right side")
    ls_lhl100_check: Optional[str] = Field(..., description="Labeling System Specifications - Label hd model - ls100")
    ls_lhl200_check: Optional[str] = Field(..., description="Labeling System Specifications - Label hd model - ls200")
    ls_lhsx_check: Optional[str] = Field(..., description="Labeling System Specifications - Label head orientation - sx left side")
    ls_ll_check: Optional[str] = Field(..., description="Labeling System Specifications - low label sensor")
    ls_none_check: Optional[str] = Field(..., description="Labeling System Specifications - none")
    ls_sd300_check: Optional[str] = Field(..., description="Labeling System Specifications - Support reel dia - 300 mm")
    ls_sd380_check: Optional[str] = Field(..., description="Labeling System Specifications - Support reel dia - 380 mm")
    ls_swb_check: Optional[str] = Field(..., description="Labeling System Specifications - Separator wheel - belt")
    ls_swnone_check: Optional[str] = Field(..., description="Labeling System Specifications - Separator wheel - none")
    ls_sws_check: Optional[str] = Field(..., description="Labeling System Specifications - Separator wheel - starwheel")
    ls_sww_check: Optional[str] = Field(..., description="Labeling System Specifications - Separator wheel - wheel")
    ls_thd_check: Optional[str] = Field(..., description="Labeling System Specifications - top hold down")
    ls_thdba_check: Optional[str] = Field(..., description="Labeling System Specifications - bottle aligner")
    ls_thdtf_check: Optional[str] = Field(..., description="Labeling System Specifications - twin feedscrew")
    ls_tl_check: Optional[str] = Field(..., description="Labeling System Specifications - Type - linear (inline)")
    ls_tr_check: Optional[str] = Field(..., description="Labeling System Specifications - Type - rotary")
    bs_cpac_check: Optional[str] = Field(..., description="BeltStar System Specifications - Cap Placement - AC")
    bs_cpbo_check: Optional[str] = Field(..., description="BeltStar System Specifications - Cap Placement - Belts – on the fly")
    bs_cpnone_check: Optional[str] = Field(..., description="BeltStar System Specifications - Cap Placement - None")
    bs_csds_check: Optional[str] = Field(..., description="BeltStar System Specifications - Cap Sorting - Docking Station")
    bs_cse_check: Optional[str] = Field(..., description="BeltStar System Specifications - Cap Sorting - Elevator")
    bs_manone_check: Optional[str] = Field(..., description="BeltStar System Specifications - Motorized Adj. - None")
    bs_may_check: Optional[str] = Field(..., description="BeltStar System Specifications - Motorized Adj. - Yes")
    bs_none_check: Optional[str] = Field(..., description="BeltStar System Specifications - None")
    bs_tadb_check: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - AC motor DC Brake")
    bs_tam_check: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - Air motor")
    bs_tb_check: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - Belts")
    bs_tf_check: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - Feedback")
    bs_tht_check: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - HMI Adj. Torque")
    bs_tmc_check: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - Magnet clutch")
    bs_ts_check: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - Servo")
    bs_tcb: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - Copy of bottle")
    bs_tcn: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - copy of neck")
    bs_ttr: Optional[str] = Field(..., description="BeltStar System Specifications - Torque - Torque Range (in-lbs)")
    cs_cdc_check: Optional[str] = Field(..., description="Capping System Specifications - Centering device - cone")
    cs_cdn_check: Optional[str] = Field(..., description="Capping System Specifications - Centering device - neck")
    cs_cdnone_check: Optional[str] = Field(..., description="Capping System Specifications - Centering device - none")
    cs_cdt_check: Optional[str] = Field(..., description="Capping System Specifications - Centering device - tube")
    cs_cpof_check: Optional[str] = Field(..., description="Capping System Specifications - Cap placement - on the fly")
    cs_cppp_check: Optional[str] = Field(..., description="Capping System Specifications - Cap placement - pick & place")
    cs_cppt_check: Optional[str] = Field(..., description="Capping System Specifications - Cap placement - push through")
    cs_cpqty: Optional[str] = Field(..., description="Capping System Specifications - Cap placement - qty")
    cs_cpr_check: Optional[str] = Field(..., description="Capping System Specifications - Cap placement - rotary")
    cs_cpra_check: Optional[str] = Field(..., description="Capping System Specifications - Cap placement - Rotation - air")
    cs_cprs_check: Optional[str] = Field(..., description="Capping System Specifications - Cap placement - Rotation - servo")
    cs_cpsd_check: Optional[str] = Field(..., description="Capping System Specifications - Cap placement - servo up down")
    cs_cpsi_check: Optional[str] = Field(..., description="Capping System Specifications - Cap placement - servo index")
    cs_csac_check: Optional[str] = Field(..., description="Capping System Specifications - Cap sorting - acoustic cover")
    cs_csc_check: Optional[str] = Field(..., description="Capping System Specifications - Cap sorting - centrifugal")
    cs_csds_check: Optional[str] = Field(..., description="Capping System Specifications - Cap sorting - docking station")
    cs_csm_check: Optional[str] = Field(..., description="Capping System Specifications - Cap Sorting - Mechanical")
    cs_csvb_check: Optional[str] = Field(..., description="Capping System Specifications - Cap sorting - vibratory bowl (xmm)")
    cs_none_check: Optional[str] = Field(..., description="Capping System Specifications - none")
    cs_tam_check: Optional[str] = Field(..., description="Capping System Specifications - Torque - air motor")
    cs_tat_check: Optional[str] = Field(..., description="Capping System Specifications - Torque - appl. torque system tool (30 or 44)")
    cs_tcn: Optional[str] = Field(..., description="Capping System Specifications - Torque - copy of neck")
    cs_tf_check: Optional[str] = Field(..., description="Capping System Specifications - Torque - feedback")
    cs_tmc_check: Optional[str] = Field(..., description="Capping System Specifications - Torque - magnet clutch")
    cs_tqty: Optional[str] = Field(..., description="Capping System Specifications - Torque - qty")
    cs_ts_check: Optional[str] = Field(..., description="Capping System Specifications - Torque - servo")
    cs_tsc_check: Optional[str] = Field(..., description="Capping System Specifications - Torque - servo calibration sys.")
    cs_ttr: Optional[str] = Field(..., description="Capping System Specifications - Torque - torque range (in-lbs)")
    cs_bfc: Optional[str] = Field(..., description="Capping System Specifications - Bulk feeder - capacity (ft3)")
    cs_bfc_check: Optional[str] = Field(..., description="Capping System Specifications - Bulk feeder - cover")
    cs_bfeg_check: Optional[str] = Field(..., description="Capping System Specifications- Bulk feeder - elevator (giraffe)")
    cs_bfnone_check: Optional[str] = Field(..., description="Capping System Specifications- Bulk feeder - none")
    cs_bfpv_check: Optional[str] = Field(..., description="Capping System Specifications- Bulk feeder - pedestal vibratory")
    cs_cse_check: Optional[str] = Field(..., description="Capping System Specifications - Cap sorting elevator")
    cs_tac_check: Optional[str] = Field(..., description="Capping System Specifications - Tube aligner - cone")
    cs_tagd_check: Optional[str] = Field(..., description="Capping System Specifications - Tube aligner - grip & dive")
    cs_tanone_check: Optional[str] = Field(..., description="Capping System Specifications - Tube aligner - none")
    cs_tcb: Optional[str] = Field(..., description="Capping System Specifications - Torque - copy of bottle")
    ps_none_check: Optional[str] = Field(..., description="Plugging System Specifications - none")
    ps_plm_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug Placement - Mechanical")
    ps_psm_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug Sorting - Mechanical")
    ps_bfc: Optional[str] = Field(..., description="Plugging System Specifications - Bulk feeder - capacity (ft3)")
    ps_bfe_check: Optional[str] = Field(..., description="Plugging System Specifications - Bulk feeder - electric")
    ps_bfeg_check: Optional[str] = Field(..., description="Plugging System Specifications - Bulk feeder - elevator (giraffe)")
    ps_bfnone_check: Optional[str] = Field(..., description="Plugging System Specifications - Bulk feeder - none")
    ps_bfp_check: Optional[str] = Field(..., description="Plugging System Specifications - Bulk feeder - pneumatic")
    ps_bfpv_check: Optional[str] = Field(..., description="Plugging System Specifications - Bulk feeder - pedestal vibratory")
    ps_plpp_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug placement - pick & place")
    ps_plpt_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug placement - push through")
    ps_plqty: Optional[str] = Field(..., description="Plugging System Specifications - Plug placement - qty")
    ps_plr_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug placement - rotary")
    ps_plv_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug placement - vacuum")
    ps_psac_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug sorting acoustic cover")
    ps_psc_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug sorting - centrifugal")
    ps_psds_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug sorting - docking station")
    ps_psnone_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug sorting - none")
    ps_psvb_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug sorting - vibratory bowl (?mm)")
    ps_pse_check: Optional[str] = Field(..., description="Plugging System Specifications - Plug sorting - elevator")
    c_cn_check: Optional[str] = Field(..., description="Cottoner - Cotton Bin - No")
    c_cy_check: Optional[str] = Field(..., description="Cottoner - Cotton Bin - Yes")
    c_none_check: Optional[str] = Field(..., description="Cottoner - None")
    c_sp_check: Optional[str] = Field(..., description="Cottoner - Sensing - Presence")
    c_sh_check: Optional[str] = Field(..., description="Cottoner - Sensing - High")
    d_bf_pv_check: Optional[str] = Field(..., description="Desiccant - Bulk feeder - pedestal vibratory")
    d_bfc_check: Optional[str] = Field(..., description="Desiccant - Bulk feeder - cover")
    d_bfe_check: Optional[str] = Field(..., description="Desiccant - Bulk feeder - elevator")
    d_bfi_check: Optional[str] = Field(..., description="Desiccant - Bulk feeder - internal")
    d_none_check: Optional[str] = Field(..., description="Desiccant - none")
    d_tc_check: Optional[str] = Field(..., description="Desiccant - Type - cannister")
    d_trp_check: Optional[str] = Field(..., description="Desiccant - Type - roll / pouch")
    gp_laf_check: Optional[str] = Field(..., description="Gas Purge - Location/Type - after fill")
    gp_latf_check: Optional[str] = Field(..., description="Gas Purge - Location/Type - at fill st.")
    gp_lbf_check: Optional[str] = Field(..., description="Gas Purge - Location/Type - before fill st")
    gp_lqty: Optional[str] = Field(..., description="Gas Purge - Location/Type - qty")
    gp_lt_check: Optional[str] = Field(..., description="Gas Purge - Location/Type - tunnel")
    gp_none_check: Optional[str] = Field(..., description="Gas Purge - none")
    gp_ta_check: Optional[str] = Field(..., description="Gas Purge - Type - argon")
    gp_tn_check: Optional[str] = Field(..., description="Gas Purge - Type - nitrogen")
    lf_cnone_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Cleaning - none")
    lf_cns: Optional[str] = Field(..., description="Liquid Filling System Specifications - Cleaning - no. of stations")
    lf_coc_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Cleaning - ionization cleaning")
    lf_ctg_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Cleaning - touch & go (c.i.p. man. sys)")
    lf_cvac_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Cleaning - vacuum air cleaning")
    lf_gsds_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Gutter system - drip style")
    lf_gsnone_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Gutter system - none")
    lf_gsp_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Gutter system - prime/purge/rinse")
    lf_nb1_2_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body size - 1/2\"")
    lf_nb1_4_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body size - 1/4\"")
    lf_nb10_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body size - 10mm")
    lf_nb12_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body size - 12mm")
    lf_nb1_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body size - 1\"")
    lf_nb3_8_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body size - 3/8\"")
    lf_nb5_8_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body size - 5/8\"")
    lf_nb6_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body size - 6 mm")
    lf_nb8_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body size - 8mm")
    lf_nb3_4_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle body type - 3/4\"")
    lf_nson_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - offset nozzle bar")
    lf_ntd_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - double wall nitro & fill")
    lf_ntdq: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - double wall nitro & fill - qty")
    lf_nti_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - ibso")
    lf_ntiq: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - ibso - qty")
    lf_nto_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - obso")
    lf_ntoq: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - obso - qty")
    lf_nts_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - straight")
    lf_ntsq: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - straight - qty")
    lf_ntsv_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - straight with check valve")
    lf_ntsvq: Optional[str] = Field(..., description="Liquid Filling System Specifications - Nozzle type - straight with check valve - qty")
    lf_ocw_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Options - check weighing (tare in/out)")
    lf_onc: Optional[str] = Field(..., description="Liquid Filling System Specifications - Options - no. of cells")
    lf_p1000: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - 1000cc (qty)")
    lf_p100: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - 100cc (qty)")
    lf_p10: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - 10cc (qty)")
    lf_p250: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - 250cc (qty)")
    lf_p500: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - 500cc (qty)")
    lf_p50: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - 50cc (qty)")
    lf_p850: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - 850cc (qty)")
    lf_phc_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - hard chrome")
    lf_pmm: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - mass meter (qty)")
    lf_pnone_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - none")
    lf_pother: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump - Other")
    lf_ptl_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump type - liquid/semi")
    lf_ptp_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump type - pneumatic")
    lf_pts_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump type - servo (qty)")
    lf_ptsb_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump type - servo bottom-up fill")
    lf_ptsh_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump type - steel heart (peristaltic)")
    lf_ptv_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump type - volumetric")
    lf_ptvi_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump type - viscous")
    lf_ptpd_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Pump type - positive displacement")
    lf_vta_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Valve type - air pilot")
    lf_vtbw_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Valve type - ball weight")
    lf_vtnone_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Valve type - none")
    lf_vtr_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Valve type - rotary")
    lf_cdc_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Centering device - cone")
    lf_cdn_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Centering device - neck")
    lf_cdnone_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Centering device - none")
    lf_th100_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - 100l")
    lf_th18_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - 18l")
    lf_th60_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - 60l")
    lf_tha_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - agitator")
    lf_thchz: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - customer hose size (id) or tri-clamp")
    lf_the_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - electropolished")
    lf_thh_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - hopper")
    lf_thitp_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - incl. transfer pump")
    lf_thj_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - jacketed")
    lf_thnone_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - none")
    lf_tho: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - other")
    lf_thsb_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - spray ball")
    lf_tht_check: Optional[str] = Field(..., description="Liquid Filling System Specifications - Tank - tank")
    sf_100_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Street fighter - 100")
    sf_1_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Street fighter - 1")
    sf_2_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Street fighter - 2")
    sf_lf100_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Lift fighter - 100l")
    sf_lf_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Lift fighter - sf_lf_check")
    sf_lfi_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Lift fighter - interlocked")
    sf_lflc_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Lift fighter - load cells")
    sf_lfna_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Lift fighter - no air")
    sf_lftah_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Lift fighter - twin axis hmi")
    sf_nf1_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - No. of funnels - 1")
    sf_nf2_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - No. of funnels - 2")
    sf_nf5_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - No. of funnels - 5")
    sf_none_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - None")
    sf_cs_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Cleaning stn")
    sf_de_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Hopper - dust ext.")
    sf_h10_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Hopper - 10l")
    sf_h60_check: Optional[str] = Field(..., description="Street Fighter Tablet Counter - Hopper - 60l")
    rj_bc_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - bar code")
    rj_ch_check: Optional[str] = Field(..., description="Reject / Inspection System - Reject method - chute")
    rj_comm: Optional[str] = Field(..., description="Reject / Inspection System - comments")
    rj_cp_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - cap prs.")
    rj_hc_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - skewed cap")
    rj_hs_check: Optional[str] = Field(..., description="Reject / Inspection System - Reject method - high speed")
    rj_lk_check: Optional[str] = Field(..., description="Reject / Inspection System - Reject method - lockable")
    rj_lp_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - label prs")
    rj_lpo_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - label position")
    rj_lr_check: Optional[str] = Field(..., description="Reject / Inspection System - Reject method - linear")
    rj_nf_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - no foil")
    rj_op_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - overcap prs")
    rj_or_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - ocr")
    rj_ov_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - ocv")
    rj_pp_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - pintle prs")
    rj_sl_check: Optional[str] = Field(..., description="Reject / Inspection System - Reject method - starwheel")
    rj_sp_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - stem prs")
    rj_tk_check: Optional[str] = Field(..., description="Reject / Inspection System - Reject method - track")
    rj_tq_check: Optional[str] = Field(..., description="Reject / Inspection System - Inspect for - torque")
    rj_ty_check: Optional[str] = Field(..., description="Reject / Inspection System - Reject method - tray")
    rj_con_check: Optional[str] = Field(..., description="Conveyor Specifications - Reject method - conveyor")
    tb_39_check: Optional[str] = Field(..., description="Turn Tables - 39\"")
    tb_48_check: Optional[str] = Field(..., description="Turn Tables - 48\"")
    tb_60_check: Optional[str] = Field(..., description="Turn Tables - 60\"")
    tb_buf_check: Optional[str] = Field(..., description="Turn Tables - buffer")
    tb_iwot_check: Optional[str] = Field(..., description="Turn Tables - infeed w/o tray")
    tb_iwt_check: Optional[str] = Field(..., description="Turn Tables - infeed table w/tray")
    tb_or_check: Optional[str] = Field(..., description="Turn Tables - orientor")
    tb_owot_check: Optional[str] = Field(..., description="Turn Tables - outfeed w/o tray")
    tb_owt_check: Optional[str] = Field(..., description="Turn Tables - outfeed table w/tray")
    batch_at_check: Optional[str] = Field(..., description="Control & Programming Specifications - Batch / Data Report - Audit Trail")
    batch_none_check: Optional[str] = Field(..., description="Control & Programming Specifications - Batch / Data Report - None")
    batch_sht_check: Optional[str] = Field(..., description="Control & Programming Specifications - Batch / Data Report - Summary Header with Tracking")
    batch_yes15_check: Optional[str] = Field(..., description="Control & Programming Specifications - Batch / Data Report - Yes (requires 15\" HMI)")
    blt_audible_check: Optional[str] = Field(..., description="Control & Programming Specifications - Beacon Light Tower - Audible")
    blt_green_check: Optional[str] = Field(..., description="Control & Programming Specifications - Beacon Light Tower - Green")
    blt_none_check: Optional[str] = Field(..., description="Control & Programming Specifications - Beacon Light Tower - None")
    blt_red_check: Optional[str] = Field(..., description="Control & Programming Specifications - Beacon Light Tower - Red")
    blt_yellow_check: Optional[str] = Field(..., description="Control & Programming Specifications - Beacon Light Tower - Yellow")
    cpp_1axis_check: Optional[str] = Field(..., description="Control & Programming Specifications - Control Panel Post - 1 Axis")
    cpp_2axis_check: Optional[str] = Field(..., description="Control & Programming Specifications - Control Panel Post - 2 Axis")
    cpp_3axis_check: Optional[str] = Field(..., description="Control & Programming Specifications - Control Panel Post - 3 Axis")
    cpp_fixed_check: Optional[str] = Field(..., description="Control & Programming Specifications - Control Panel Post - Fixed (STD for Explosive Environment)")
    cps_ep_check: Optional[str] = Field(..., description="Control & Programming Specifications - Explosion proof")
    cps_none_check: Optional[str] = Field(..., description="Control & Programming Specifications - Explosion proof - none")
    etr_10hmi_check: Optional[str] = Field(..., description="Control & Programming Specifications - Electronic torque readout - Size - 10\"")
    etr_none_check: Optional[str] = Field(..., description="Control & Programming Specifications - Electronic torque readout - none")
    hmi_allenb_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - Allen Bradley")
    hmi_b_r_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - B & R")
    hmi_pc_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - PC Upgrade")
    hmi_pv10_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - Allen Bradley - Size - 10\"")
    hmi_pv7_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - Allen Bradley - Size - 7\"")
    hmi_size10_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - B & R - Size - 10\"")
    hmi_size15_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - PC upgrade - Size - 15\"")
    hmi_size5_7_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - B & R - Size - 5.7\" n/a for vision")
    lan_e_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - Language - English")
    lan_f_check: Optional[str] = Field(..., description="Control & Programming Specifications - HMI - Language - French")
    plc_allenb_check: Optional[str] = Field(..., description="Control & Programming Specifications - PLC - Allen Bradley")
    plc_b_r_check: Optional[str] = Field(..., description="Control & Programming Specifications - PLC - B & R")
    plc_compactl_check: Optional[str] = Field(..., description="Control & Programming Specifications - PLC - CompactLogix")
    plc_controll_check: Optional[str] = Field(..., description="Control & Programming Specifications - PLC - ControlLogix")
    rts_co_check: Optional[str] = Field(..., description="Control & Programming Specifications - connection only")
    rts_none_check: Optional[str] = Field(..., description="Control & Programming Specifications - none")
    rts_secomea_check: Optional[str] = Field(..., description="Control & Programming Specifications - remote technical service (secomea)")
    plug_ss304_check: Optional[str] = Field(..., description="Plugging System Specifications - ss 304")
    plug_ss316_check: Optional[str] = Field(..., description="Plugging System Specifications - ss 316")
    machine: Optional[str] = Field(..., description="Basic Information - Machine")
    production_speed: Optional[str] = Field(..., description="Order Identification - Production speed")
    quote: Optional[str] = Field(..., description="Order Identification - Quote")
    amps: Optional[str] = Field(..., description="Utility Specifications - AMPS")
    ce_c1d2_check: Optional[str] = Field(..., description="Utility Specifications - Certification - Class1 Div 2")
    ce_csa_check: Optional[str] = Field(..., description="Utility Specifications - Certification - CSA")
    ce_expl_check: Optional[str] = Field(..., description="Utility Specifications - Certification - Explosion")
    cfm: Optional[str] = Field(..., description="Utility Specifications - CFM")
    conformity_csa_check: Optional[str] = Field(..., description="Utility Specifications - csa")
    country: Optional[str] = Field(..., description="Utility Specifications - country")
    hz: Optional[str] = Field(..., description="Utility Specifications - Hz")
    phases: Optional[str] = Field(..., description="Utility Specifications - phases")
    psi: Optional[str] = Field(..., description="Utility Specifications - PSI")
    voltage: Optional[str] = Field(..., description="Utility Specifications - Voltage")
    options_listing: Optional[str] = Field(..., description="Option Listing - Additional Quoted Options")
    customer: Optional[str] = Field(..., description="GENERAL ORDER ACKNOWLEDGEMENT > Customer")
    direction: Optional[str] = Field(..., description="GENERAL ORDER ACKNOWLEDGEMENT > Direction")
    ce_none_check: Optional[str] = Field(..., description="Utility Specifications > CE None Check")
    bs_984_check: Optional[str] = Field(..., description="BASIC SYSTEMS > Mechanical Basic Machine configuration > Sortstar 18ft3 220VAC 3 Phases LEFT TO RIGHT")
    bs_1230_check: Optional[str] = Field(..., description="BASIC SYSTEMS > Mechanical Basic Machine configuration > Sortstar 18ft3 220VAC 3 Phases RIGHT TO LEFT")
    bs_985_check: Optional[str] = Field(..., description="BASIC SYSTEMS > Mechanical Basic Machine configuration > Sortstar 18ft3 480VAC & 380VAC 3 Phases LEFT TO RIGHT")
    bs_1229_check: Optional[str] = Field(..., description="BASIC SYSTEMS > Mechanical Basic Machine configuration > Sortstar 18ft3 480VAC & 380VAC 3 Phases RIGHT TO LEFT")
    bs_1264_check: Optional[str] = Field(..., description="BASIC SYSTEMS > Mechanical Basic Machine configuration > Sortstar 24ft3 220VAC 3 Phases LEFT TO RIGHT")
    bs_1265_check: Optional[str] = Field(..., description="BASIC SYSTEMS > Mechanical Basic Machine configuration > Sortstar 24ft3 480VAC & 380VAC 3 Phases LEFT TO RIGHT")
    op_2409_check: Optional[str] = Field(..., description="OPTIONAL SYSTEMS > Guarding System > Lexan Euroguard Top Cover")
    op_ias_check: Optional[str] = Field(..., description="OPTIONAL SYSTEMS > Guarding System > Ionized Air System")
    op_nrck_check: Optional[str] = Field(..., description="OPTIONAL SYSTEMS > Guarding System > Requires Cap Kit")
    el_0369_check: Optional[str] = Field(..., description="OPTIONAL SYSTEMS > Electrical > Stack Light with Buzzer Option")
    cpp_2axis_check: Optional[str] = Field(..., description="OPTIONAL SYSTEMS > Control Specifications > Control Panel Post 2 Axis – U-shaped")
    pt_pts_check: Optional[str] = Field(..., description="OPTIONAL SYSTEMS > Packaging & Transport & Warranty & Install & Spares > Packaging type Skid")
